### ISSUE TITLE
error 'NoneType' object has no attribute 'update'

### ISSUE THREAD

**Issue by superuser5** [richiercyrus/Venator#15]
getting error below:

$ python -V
Python 2.7.16
$ sudo /usr/bin/python ./Venator.py
Password:
\
__     __               _
\ \   / /__ _ __   __ _| |_ ___  _ __
 \ \ / / _ \ '_ \ / _` | __/ _ \| '__|
  \ V /  __/ | | | (_| | || (_) | |
   \_/ \___|_| |_|\__,_|\__\___/|_|

[+] Gathering users on the system.
[+] Gathering System Intergrity Protection status.
[+] Getting system information.
[+] Gathering Install History data.
[+] Gathering Gatekeeper status.
[+] Gathering current network connections.
[+] Gathering Environment Variables.
[+] Gathering Periodic Scripts.
[+] Gathering current cron jobs.
[+] Gathering Emond Rules.
[+] Gathering Launch Agent data.
[+] Gathering any shell startup scripts ('~/.bash_profile', etc.)
[+] Gathering Launch Daemon data.
[+] Gathering Kernel Extensions data.
[+] Gathering Applications for each user.
[+] Gathering installed Event Taps.
[+] Gathering Bash History data.
[+] Gathering Launch Agent data.
Traceback (most recent call last):
  File "./Venator.py", line 725, in <module>
    getLaunchAgents(userLaunchAgent,outfile)
  File "./Venator.py", line 231, in getLaunchAgents
    parsedAgent.update({"module":"launch_agents"})
AttributeError: 'NoneType' object has no attribute 'update'

**Comment by felixguerrero12** [comment]
https://github.com/richiercyrus/Venator/blob/a1b628695d1eaf4d1b63fa4ad316c5ec589e717b/Venator.py#L724

- Does it need an forward slash at the end of the line? All the other ones have a forward slash'.
/Users/' + Users + '/Library/Safari/Extensions/'
