### ISSUE TITLE
Errors on macOS 10.14.4

### ISSUE THREAD

**Issue by JayBrown** [richiercyrus/Venator#5]
Here's the output:

```
[+] Gathering Kernel Extensions data.
Traceback (most recent call last):
  File "~/.local/bin/Venator.py", line 620, in <module>
    getLaunchDaemons('/Library/LaunchDaemons',outfile),getKext(sipStatus,'/Library/Extensions',outfile),getApps('/Applications',outfile),getEventTaps(outfile),getBashHistory(outfile,lst_of_users)]
  File "~/.local/bin/Venator.py", line 384, in getKext
    kextPlist = plistlib.readPlist(os.path.join(root, name))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 78, in readPlist
    rootObject = p.parse(pathOrFile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 406, in parse
    parser.ParseFile(fileobj)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 8
```

**Comment by richiercyrus** [comment]
I'll take a look at this ASAP. Thanks!

**Comment by richiercyrus** [comment]
Just pushed a fix out. See if that takes care of the issue. It's a temp fix but I imagine that it came across a binary plist it couldn't handle or a plist that isn't formed in a standard way.

**Comment by JayBrown** [comment]
This time it got past the extensions scan, but stopped with error during the applications scan.

```
[+] Gathering Applications for each user.
Traceback (most recent call last):
  File "~/.local/bin/Venator.py", line 629, in <module>
    getLaunchDaemons('/Library/LaunchDaemons',outfile),getKext(sipStatus,'/Library/Extensions',outfile),getApps('/Applications',outfile),getEventTaps(outfile),getBashHistory(outfile,lst_of_users)]
  File "~/.local/bin/Venator.py", line 549, in getApps
    apps = parseApp(app)
  File "~/.local/bin/Venator.py", line 498, in parseApp
    executable_path = app+"/Contents/MacOS/"+executable
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 25: ordinal not in range(128)
```

**Comment by WardsParadox** [comment]
Having issues with 10.14.4 at KEXT using latest pulled 5 mins ago. Looks a bit different than @JayBrown's initial report but still related.
```
[+] Gathering Kernel Extensions data.
Traceback (most recent call last):
  File "Venator.py", line 629, in <module>
    getLaunchDaemons('/Library/LaunchDaemons',outfile),getKext(sipStatus,'/Library/Extensions',outfile),getApps('/Applications',outfile),getEventTaps(outfile),getBashHistory(outfile,lst_of_users)]
  File "Venator.py", line 382, in getKext
    executable_path = kextPath+"/"+kext+"/Contents/MacOS/"+executable
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by richiercyrus** [comment]
Stand by. Sorry for the issues around kexts.

**Comment by richiercyrus** [comment]
Attempted to take care of the issues specified. Please let me know if there are additional bugs.

**Comment by JayBrown** [comment]
Seems to work fine now.

Question: does Venator also scan for non-running apps, including those in:
~/Applications
~/Developer/Applications
/Developer/Applications
/Network/Applications
/Network/Developer/Applications
etc.?

**Comment by richiercyrus** [comment]
Not currently, but I can add that to the roadmap for additional content to the applications module. I like that idea!

**Comment by WardsParadox** [comment]
Current HEAD fixes my issue, thanks @richiercyrus! This looks really useful for me :)
